// src/pages/api/shoppingLists.js (UPDATED)

import { endpointHandler } from '../../lib/handler';
import { CreateListDtoIn } from '../../lib/schemas';
import shoppingListDao from '../../dao/shoppingList-dao'; // <<< IMPORT DAO

const COMMAND = "shoppingList/createList";
const REQUIRED_PROFILE = "User"; 

// Main request handler for all HTTP methods on this path
export default async function handler(req, res) {
  if (req.method === 'POST') {
    await endpointHandler(
      req,
      res,
      CreateListDtoIn, 
      REQUIRED_PROFILE, 
      // Change: callback is now async and calls the DAO
      async (dtoIn, userId) => {
        // --- REAL APPLICATION LOGIC ---
        const dtoOut = await shoppingListDao.create(dtoIn, userId);
        return dtoOut; // Return the DTO-Out generated by the DAO
      }
    );
  } else {
    // Handle any other methods
    res.status(405).json({ 
        code: "method-not-allowed", 
        message: `${req.method} method not allowed for this command.` 
    });
  }
}