// src/pages/api/shoppingLists.js

import { endpointHandler, generateDtoOut } from '../../lib/handler';
import { CreateListDtoIn } from '../../lib/schemas';

const COMMAND = "shoppingList/createList";
const REQUIRED_PROFILE = "User"; // As per your authorization matrix

// Main request handler for all HTTP methods on this path
export default async function handler(req, res) {
  if (req.method === 'POST') {
    // We pass the request, response, the schema for validation, the required role, 
    // and a callback function that represents the application logic.
    await endpointHandler(
      req,
      res,
      CreateListDtoIn, // Zod schema for validation
      REQUIRED_PROFILE, // Required Profile for authorization check
      (dtoIn, userId) => {
        // --- THIS IS THE APPLICATION LOGIC MOCK ---
        // We are NOT implementing the actual creation logic.
        // We just prepare the DtoOut, which echoes the input (dtoIn)
        // and includes mock system data, as required by the assignment.
        
        // Mock data for the 'created list' response (typically generated by a database)
        const mockListId = "f5f12e12-b062-430c-8367-b7156d11e1f7";

        const dtoOutData = {
          id: mockListId,
          name: dtoIn.name,
          ownerId: userId,
          state: "active"
        };

        // Combine the mock data with the mandatory system fields and return the final DtoOut
        return generateDtoOut(dtoOutData, userId, COMMAND);
      }
    );
  } else {
    // Handle any other methods (GET, PUT, DELETE) that are not implemented here
    res.status(405).json({ 
        code: "method-not-allowed", 
        message: `${req.method} method not allowed for this command.` 
    });
  }
}